apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: kube-ops
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec:
#      hostAliases:
#      - ip: 192.168.19.31
#        hostnames:
#        - gerrit.bochtec.com
#        - sonarqube.bochtec.com
#        - jenkins.bochtec.com
      terminationGracePeriodSeconds: 10
      serviceAccount: jenkins
      initContainers:
      - name: init
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          chown 1000 /var/jenkins_home
        securityContext:
          privileged: true
        volumeMounts:
        - name: jenkinshome
          subPath: jenkins
          mountPath: /var/jenkins_home
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        - containerPort: 50000
          name: agent
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12 
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 12
        volumeMounts:
        - name: jenkinshome
          subPath: jenkins
          mountPath: /var/jenkins_home
        env:
        - name: JAVA_OPTS
          value: -Xms512m -Xmx2048m -Difile.encoding=utf-8 -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400 -Duser.timezone=Asia/Shanghai
      securityContext:
        fsGroup: 1000
      volumes:
      - name: jenkinshome
        persistentVolumeClaim:
          claimName: jenkins-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: kube-ops
  labels:
    app: jenkins
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31000
    - name: agent
      port: 50000
      protocol: TCP
      targetPort: 50000
      nodePort: 31001
  selector:
    app: jenkins
  type: NodePort
#  type: ClusterIP

#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: jenkins-ingress
#  namespace: kube-ops
#  labels:
#    app: jenkins
#spec:
#  rules:
#  - host: jenkins.bochtec.com
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: jenkins
#          servicePort: 8080
