apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerrit-nginx
  namespace: kube-ops
  labels:
    app: gerrit-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerrit-nginx
  template:
    metadata:
      labels:
        app: gerrit-nginx
    spec:
      containers:
      - name: gerrit-nginx
        image: nginx:1.17.9-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: conf
          #mountPath: /etc/nginx/conf.d/gerrit.conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: gerrit.conf
        - name: password
          mountPath: /etc/nginx/password
          subPath: password
      volumes:
        - name: conf
          configMap:
            name: gerrit-config
            items:
              - key: gerrit.conf
                path: gerrit.conf
                mode: 0644
        - name: password
          configMap:
            name: gerrit-config
            items:
              - key: password
                path: password
                mode: 0644

---
apiVersion: v1
kind: Service
metadata:
  name: gerrit-nginx
  namespace: kube-ops
  labels:
    app: gerrit-nginx
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: gerrit-nginx
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gerrit-nginx-ingress
  namespace: kube-ops
  labels:
    app: gerrit-nginx
spec:
  rules:
  - host: gerrit.bochtec.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gerrit-nginx
          servicePort: 80
