apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerrit-httpd
  namespace: kube-ops
  labels:
    app: gerrit-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerrit-httpd
  template:
    metadata:
      labels:
        app: gerrit-httpd
    spec:
      containers:
      - name: gerrit-httpd
        image: httpd:2.4.43-alpine
        ports:
        - containerPort: 80
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "LoadModule proxy_module modules/mod_proxy.so" >> /usr/local/apache2/conf/httpd.conf
            echo "LoadModule proxy_http_module modules/mod_proxy_http.so" >> /usr/local/apache2/conf/httpd.conf
            echo "Include conf/extra/httpd-gerrit.conf" >> /usr/local/apache2/conf/httpd.conf
            /usr/local/bin/httpd-foreground
        volumeMounts:
        - name: conf
          mountPath: /usr/local/apache2/conf/extra/httpd-gerrit.conf
          subPath: httpd-gerrit.conf
        - name: password
          mountPath: /usr/local/apache2/conf/password
          subPath: password
      volumes:
        - name: conf
          configMap:
            name: gerrit-config
            items:
              - key: httpd-gerrit.conf
                path: httpd-gerrit.conf
                mode: 0644
        - name: password
          configMap:
            name: gerrit-config
            items:
              - key: password
                path: password
                mode: 0644

---
apiVersion: v1
kind: Service
metadata:
  name: gerrit-httpd
  namespace: kube-ops
  labels:
    app: gerrit-httpd
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31005
  selector:
    app: gerrit-httpd
  type: NodePort
#  type: ClusterIP

#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: gerrit-httpd-ingress
#  namespace: kube-ops
#  labels:
#    app: gerrit-httpd
#spec:
#  rules:
#  - host: gerrit.bochtec.com
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: gerrit-httpd
#          servicePort: 80
