apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerrit
  namespace: kube-ops
  labels:
    app: gerrit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerrit
  template:
    metadata:
      name: gerrit
      labels:
        app: gerrit
    spec:
      hostAliases:
      - ip: 192.168.19.31
        hostnames:
        - gerrit.bochtec.com
      containers:
      - name: gerrit
        image: openfrontier/gerrit:3.1.3
        #image: openfrontier/gerrit:2.15.18
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        ports:
        - name: http
          containerPort: 8080
        - name: ssh
          containerPort: 31006
        volumeMounts:
        - mountPath: /var/gerrit/review_site
          name: gerrit
        env:
        - name: AUTH_TYPE
          value: "HTTP"
        - name: WEBURL
          value: "http://192.168.19.29:31005"
        - name: LISTEN_ADDR
          value: "*:31006"
        - name: SMTP_SERVER
          value: "smtp.bochtec.com"
        - name: SMTP_SERVER_PORT
          value: "465"
        - name: SMTP_ENCRYPTION
          value: "ssl"
        - name: SMTP_USER
          value: "baosong@bochtec.com"
        - name: SMTP_PASS
          value: "Nasong819"
        - name: SMTP_FROM
          value: "baosong@bochtec.com"
        - name: DATABASE_TYPE
          value: "mysql"
        - name: DATABASE_HOSTNAME
          value: "mysql-gerrit"
        - name: DATABASE_PORT
          value: "3306"
#        - name: DATABASE_TYPE
#          value: "postgresql"
#        - name: DATABASE_HOSTNAME
#          value: "postgres-gerrit"
#        - name: DATABASE_PORT
#          value: "5432"
        - name: DATABASE_DATABASE
          value: "reviewdb"
        - name: DATABASE_USERNAME
          value: "gerrit"
        - name: DATABASE_PASSWORD
          value: "gerrit123"
        - name: GERRIT_INIT_ARGS
          value: "--install-all-plugins"
      initContainers:
      - name: init
        image: openfrontier/gerrit:3.1.3
        securityContext:
          privileged: true
        command:
        - java
        - -jar
        - /var/gerrit/gerrit.war
        - init
        - -b
        - --no-auto-start
        - -d
        - /var/gerrit/review_site/
        env:
        - name: AUTH_TYPE
          value: "HTTP"
        - name: WEBURL
          value: "http://192.168.19.29:31005"
        - name: LISTEN_ADDR
          value: "*:31006"
        - name: SMTP_SERVER
          value: "smtp.bochtec.com"
        - name: SMTP_SERVER_PORT
          value: "465"
        - name: SMTP_ENCRYPTION
          value: "ssl"
        - name: SMTP_USER
          value: "baosong@bochtec.com"
        - name: SMTP_PASS
          value: "Nasong819"
        - name: SMTP_FROM
          value: "baosong@bochtec.com"
        - name: DATABASE_TYPE
          value: "mysql"
        - name: DATABASE_HOSTNAME
          value: "mysql-gerrit"
        - name: DATABASE_PORT
          value: "3306"
#        - name: DATABASE_TYPE
#          value: "postgresql"
#        - name: DATABASE_HOSTNAME
#          value: "postgres-gerrit"
#        - name: DATABASE_PORT
#          value: "5432"
        - name: DATABASE_DATABASE
          value: "reviewdb"
        - name: DATABASE_USERNAME
          value: "gerrit"
        - name: DATABASE_PASSWORD
          value: "gerrit123"
        - name: GERRIT_INIT_ARGS
          value: "--install-all-plugins"
        volumeMounts:
        - mountPath: /var/gerrit/review_site
          name: gerrit
      - name: reindex
        image: openfrontier/gerrit:3.1.3
        securityContext:
          privileged: true
        command:
        - java
        - -jar
        - /var/gerrit/review_site/bin/gerrit.war
        - reindex
        - --show-stack-trace
        - -d
        - /var/gerrit/review_site/
        env:
        - name: AUTH_TYPE
          value: "HTTP"
        - name: WEBURL
          value: "http://192.168.19.29:31005"
        - name: LISTEN_ADDR
          value: "*:31006"
        - name: SMTP_SERVER
          value: "smtp.bochtec.com"
        - name: SMTP_SERVER_PORT
          value: "465"
        - name: SMTP_ENCRYPTION
          value: "ssl"
        - name: SMTP_USER
          value: "baosong@bochtec.com"
        - name: SMTP_PASS
          value: "Nasong819"
        - name: SMTP_FROM
          value: "baosong@bochtec.com"
        - name: DATABASE_TYPE
          value: "mysql"
        - name: DATABASE_HOSTNAME
          value: "mysql-gerrit"
        - name: DATABASE_PORT
          value: "3306"
#        - name: DATABASE_TYPE
#          value: "postgresql"
#        - name: DATABASE_HOSTNAME
#          value: "postgres-gerrit"
#        - name: DATABASE_PORT
#          value: "5432"
        - name: DATABASE_DATABASE
          value: "reviewdb"
        - name: DATABASE_USERNAME
          value: "gerrit"
        - name: DATABASE_PASSWORD
          value: "gerrit123"
        - name: GERRIT_INIT_ARGS
          value: "--install-all-plugins"
        volumeMounts:
        - mountPath: /var/gerrit/review_site
          name: gerrit
      volumes:
        - name: gerrit
          persistentVolumeClaim:
            claimName: gerrit-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: gerrit-ssh
  namespace: kube-ops
  labels:
    app: gerrit-ssh
spec:
  ports:
    - name: ssh
      port: 31006
      targetPort: 31006
      nodePort: 31006
  type: NodePort
  selector:
    app: gerrit

---
apiVersion: v1
kind: Service
metadata:
  name: gerrit
  namespace: kube-ops
  labels:
    app: gerrit
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: gerrit
