apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-gerrit-config
  namespace: kube-ops
  labels:
    app: mysql-gerrit
data:
  my.cnf: |
    [mysqld]
       skip_ssl
       character-set-server = utf8mb4
       collation-server = utf8mb4_unicode_ci
       explicit_defaults_for_timestamp = 1
    [client]
       default-character-set = utf8mb4
