apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-gerrit
  namespace: kube-ops
  labels:
    app: postgres-gerrit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-gerrit
  template:
    metadata:
      labels:
        app: postgres-gerrit
    spec:
      containers:
      - name: postgres-gerrit
        image: postgres:11.7
        imagePullPolicy: IfNotPresent
        ports:
        - name: postgres-gerrit
          containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "reviewdb"
        - name: POSTGRES_USER
          value: "gerrit"
        - name: POSTGRES_PASSWORD
          value: "gerrit123"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb-gerrit
      volumes:
        - name: postgredb-gerrit
          persistentVolumeClaim:
            claimName: postgres-gerrit-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-gerrit
  namespace: kube-ops
  labels:
    app: postgres-gerrit
spec:
  ports:
    - name: postgres-gerrit
      port: 5432
      targetPort: postgres-gerrit
  selector:
    app: postgres-gerrit
