kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
  namespace: kube-ops
  labels:
    name: jenkins-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins
  hostPath:
    path: /share/kube-ops

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: jenkins
  selector:
    matchLabels:
      name: jenkins-hostpath
