apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-sonar
  namespace: kube-ops
  labels:
    app: postgres-sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-sonar
  template:
    metadata:
      name: postgres-sonar
      labels:
        app: postgres-sonar
    spec:
      containers:
      - name: postgres-sonar
        image: postgres:11.7
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: postgres-sonar
          containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "sonarDB"
        - name: POSTGRES_USER
          value: "sonar"
        - name: POSTGRES_PASSWORD
          value: "sonar123"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb-sonar
      volumes:
        - name: postgredb-sonar
          persistentVolumeClaim:
            claimName: postgres-sonar-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-sonar
  namespace: kube-ops
  labels:
    app: postgres-sonar
spec:
  ports:
    - name: postgres-sonar
      port: 5432
      targetPort: postgres-sonar
  selector:
    app: postgres-sonar
