apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-gerrit
  namespace: kube-ops
  labels:
    name: postgres-gerrit
spec:
  template:
    metadata:
      name: postgres-gerrit
      labels:
        name: postgres-gerrit
    spec:
      containers:
      - name: postgres-gerrit
        image: postgres:11.7
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: postgres-gerrit
          containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "reviewdb"
        - name: POSTGRES_USER
          value: "gerrit"
        - name: POSTGRES_PASSWORD
          value: "gerrit123"
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 1024Mi
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb-gerrit
      volumes:
        - name: postgredb-gerrit
          persistentVolumeClaim:
            claimName: postgres-gerrit-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-gerrit
  namespace: kube-ops
  labels:
    name: postgres-gerrit
spec:
  ports:
    - name: postgres-gerrit
      port: 5432
      targetPort: postgres-gerrit
  selector:
    name: postgres-gerrit
