kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-gerrit-pv
  namespace: kube-ops
  labels:
    name: postgres-gerrit-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-gerrit
  hostPath:
    path: /share/kube-ops/postgres-gerrit

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-gerrit-pvc
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: postgres-gerrit
  selector:
    matchLabels:
      name: postgres-gerrit-hostpath
